version: '2.1'
services:
  tomcat:  
    image: radgast/tomcat
    expose:
      - "8443"
    ports:
      - "8443:8443"     
    links:
      - postgres  
    depends_on: 
      postgres:
        condition: service_healthy
  
  postgres:  
    image: radgast/postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"  
    healthcheck:
      test: ["CMD-SHELL", "psql -h 'localhost' -U 'postgres' --dbname=hospital -c 'SELECT * FROM events'"]
      interval: 25s
      timeout: 8s
      retries: 6
